---
wordpress:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hostname: cloud37.knell.it
    ingressClassName: nginx
    tls: true
  mariadb:
    auth:
      database: cloud37-wp
      password: E6GZyZ2PWScT153uh7CdLRT8I409MrNA
      username: cloud37
    primary:
      persistence:
        enabled: false
  persistence:
    enabled: false
  service:
    type: ClusterIP
  serviceAccount:
    create: true
  wordpressBlogName: cloud37's Blog!
  wordpressPassword: p3rf3ctblog
  wordpressUsername: cloud37
