---
apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    name: whoami
  spec:
    rules:
    - host: whoami.knell.it
      http:
        paths:
        - backend:
            service:
              name: whoami
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - whoami.knell.it
      secretName: whoami.knell.it-tls
